### ISSUE TITLE
Build and publish the package

### ISSUE THREAD

**Issue by CallMePixelMan** [Akascape/CTkListbox#1]
Hello, your project seems great! 

But currently, because of the way we (e.i, us, developpers needing a CTkListbox) are supposed to install it, there are a some problem about managing dependencies. 
For example, if you want to upgrade your package and then publish it, I would have to keep track about your change by hand, then remove the files in my project, and then re-install the updated version manually..

A great fix would be to build and publish it to PyPi using a tool like [poetry](https://python-poetry.org/). It is really easy to use and you could probably get the job done for you in a couple or commands (`poetry init` / `poetry add customtkinter` / `poetry build` / `poetry publish`).

Thanks.

**Comment by Akascape** [comment]
I can upload this project to pypi like my other packages. Dont worry, I will upload it today.

**Comment by Akascape** [comment]
@CallMePixelMan 
Ok, so it's now uploaded to pypi: https://pypi.org/project/CTkListbox/

Use `pip install CTkListbox`
