### ISSUE TITLE
Removing whitespace in a listbox with a small amount of options

### ISSUE THREAD

**Issue by woodywinton** [Akascape/CTkListbox#10]
I can't remove the whitespace underneath these 4 options for my listbox. I have tried using the height variable. I am able to make the listbox bigger by setting say height=400, however, I am unable to reduce the height to make a perfect fit for my four items in the listbox.

[https://imgur.com/a/3pBL54w](url)

I have also tried reducing the height of the parent, but that just squished the buttons that are at the bottom of my listbox.

**Comment by Akascape** [comment]
@woodywinton 
This is not a listbox for tkinter, use within the customtkinter window (CTk()) only. Otherwise the widget will not work properly.

**Comment by Akascape** [comment]
@woodywinton 
The height issue is related to the customtkinter scrollable frame, cannot do anything currently.

**Comment by codedreamin** [comment]
@Akascape 
I believe there is currently an open pull request for the scrollable frame fix. Hopefully, it gets fixed soon.
