### ISSUE TITLE
CTkListbox's scrollbar size will freeze after another CTkListbox is created

### ISSUE THREAD

**Issue by tsouzadaSSA** [Akascape/CTkListbox#11]
CTkListbox's scrollbar size will freeze after another CTkListbox is created

Example from the code given in https://github.com/Akascape/CTkListbox.

The CTkListbox's  scrollbar will not resize for any new insert after another CTkListbox is created.

![ex1_working](https://github.com/Akascape/CTkListbox/assets/105203609/2d2addb0-73d7-4b27-a2ae-9e64ba04b1b1)
![ex2_not_working](https://github.com/Akascape/CTkListbox/assets/105203609/df9a6769-300c-4a83-9ba8-ac8efdcd7f46)
![ex3_not_working](https://github.com/Akascape/CTkListbox/assets/105203609/1a8c770f-5f7c-4123-a9d3-aa7ce500cac7)

**Comment by Akascape** [comment]
@tsouzadaSSA Are you using the latest version?

**Comment by tsouzadaSSA** [comment]
So obvious!
Working now!
Sorry for creating the issue!
