### ISSUE TITLE
I can't create CTkListbox with height less than 200

### ISSUE THREAD

**Issue by bladas** [Akascape/CTkListbox#14]
If you explicitly specify a height less than 200, it will still be created with a minimum value of 200

ist_box = CTkListbox('some parent', width=100, height=100)
list_box.place(anchor=CENTER, relx=.80, rely=.50)

**Comment by Akascape** [comment]
@bladas That is actually a problem with the ctkscrollable frame widget, ctklistbox is built in top of that so it will show the same behaviour. Issue already registered: https://github.com/TomSchimansky/CustomTkinter/issues/1660

**Comment by bladas** [comment]
@Akascape Ok, thanks for the clarification
