### ISSUE TITLE
Height value ignored during ListBox creation

### ISSUE THREAD

**Issue by alessioagresti** [Akascape/CTkListbox#19]
Hi!  CTkListbox great tool!
Unfortunately I'm not able to adjust height, only width is changing. 
I took care to install last available version but with not solving issue
Below simple code I use where "height" is ignored

txtRC=CTkListbox(tabview.tab(tabD4),width=445, height=50)
txtRC.place(x=10,y=200)

**Comment by codedreamin** [comment]
@alessioagresti
This is a known issue that comes from Customtkinter scrollable frame, the height value cannot be lower than 200.
There is currently an open pull request [https://github.com/TomSchimansky/CustomTkinter/pull/1765](url) to fix this but until it does @Akascape will not be able to correct this.

**Comment by alessioagresti** [comment]
Checking right now at CustomTkinter pull 1765 it seems since June 26 the issue of size lower than 200 was fixed

"Now the user can :

Set a height of less than 200px in ScrollableFrame if the orientation is Vertical (Default).
Set a width of less than 200px in ScrollableFrame if the orientation is Horizontal.
Change the corner radius of the Scrollbar in ScrollableFrame.
Change the cursor of the Scrollbar in ScrollableFrame (default now is 'hand 2').
Fixes issues :

https://github.com/TomSchimansky/CustomTkinter/issues/1660
https://github.com/TomSchimansky/CustomTkinter/issues/1362"

**Comment by Akascape** [comment]
@alessioagresti Yes it was fixed but not implemented in customtkinter. Once the PR gets accepted, ctklistbox will also work properly.

**Comment by alessioagresti** [comment]
I try changed myself source code as suggested. It works. Thank you!

**Comment by Akascape** [comment]
@alessioagresti @alessioagresti @codedreamin FIxed
