### ISSUE TITLE
Adding multiple modes

### ISSUE THREAD

**Issue by masuriii** [Akascape/CTkListbox#22]
The tkinter listbox has modes: tk.SINGLE, tk.BROWSE, tk.MULTIPLE, tk.EXTENDED

i would like to choose items with Shift and Ctrl or to select items with arrows

can you add this pls
sry for my eng :)

**Comment by Akascape** [comment]
@masuriii 
> The tkinter listbox has modes: tk.SINGLE, tk.BROWSE, tk.MULTIPLE, tk.EXTENDED

I have already added `multiple_selection` option.

> i would like to choose items with Shift and Ctrl or to select items with arrows

I have added shift bindings to easily select multiple options at once.
