### ISSUE TITLE
tipp: in case you get the error (TypeError: 'float' object cannot be interpreted as an integer) when trying to delete the list objects

### ISSUE THREAD

**Issue by marlon-888** [Akascape/CTkListbox#23]
If there were too many file names/objects listed in the list box and I tried to delete the entire contents of the list using the command ".delete(1.0, tk.END)", I received the following error message:

```
for i in range(index, int(last)+1):
TypeError: 'float' object cannot be interpreted as an integer
```
and nothing was deleted.

If you have the problem, use the command:

".delete(0, self.file_listbox.size() - 1)"

or:

".delete("all")"

**Comment by Akascape** [comment]
@marlon-888 Fixed
