### ISSUE TITLE
ListBox buttons sometimes disappear when taking screenshot on windows with Win+Shift+S

### ISSUE THREAD

**Issue by Sargeanthost** [Akascape/CTkListbox#28]
The buttons sometimes disappear when taking a screenshot with this accelerator. When using PrintScreen they don't disappear, nor when using the snipping tool. Correct functionality with the accelerator happens when using PrintScreen or the snipping tool, though.

First opened, W+S+S:
![image](https://github.com/Akascape/CTkListbox/assets/36427968/56216ecf-dca1-435a-b0f3-d3bdad0630d1)

After, PS:
![image](https://github.com/Akascape/CTkListbox/assets/36427968/45fa05c7-3081-4eb4-921c-fdfe02eb3779)

After, W+S+S:
![image](https://github.com/Akascape/CTkListbox/assets/36427968/283ba14a-e9db-4fef-9d00-ce073ce20446)

**Comment by Akascape** [comment]
@Sargeanthost can you clarify whether the buttons disappear from the screenshot or from the actual application itself?

**Comment by Sargeanthost** [comment]
> @Sargeanthost can you clarify whether the buttons disappear from the screenshot or from the actual application itself?

The buttons flicker really fast and then disappear, and the the screenshot area selector pop-up displays

**Comment by Akascape** [comment]
@Sargeanthost Can you check if this is happening with any other ctkbutton or ctk widget?

**Comment by Sargeanthost** [comment]
> @Sargeanthost Can you check if this is happening with any other ctkbutton or ctk widget?

Not that I could find. I have two ctkbuttons to the side of that entry widget and they stayed in their positions. I haven't tried anything else in a scrollable pane, though

**Comment by Akascape** [comment]
@Sargeanthost Please try this with other widgets placed in ctkscrollableframe and let me know!

**Comment by Akascape** [comment]
@Sargeanthost Update and check again
