### ISSUE TITLE
The hex colour code turns up as a selection in the list on post-initiation configuration

### ISSUE THREAD

**Issue by infiniteTesch** [Akascape/CTkListbox#34]
Trying to change the text colour but for some reason the name of items in the list gets replaced with the colour name.. 

It only occurs when I configure the text_color property post init. 

Other then that I think this widget is great! =)

**Comment by infiniteTesch** [comment]
![dsa](https://github.com/Akascape/CTkListbox/assets/122315032/f3a7a8e1-d20e-46ca-a7d3-39763a3dfcb6)

Basically, if you want to change theme on run-time, you have to restart the client to remove the hex codes. Really annoying :/

**Comment by Akascape** [comment]
@infiniteTesch Fixed, will be fine in the latest update.

**Comment by infiniteTesch** [comment]
@Akascape MVP!
