### ISSUE TITLE
Select function broke after last update

### ISSUE THREAD

**Issue by infiniteTesch** [Akascape/CTkListbox#49]
Got this error after the last update when trying to click on items in my listbox which is popualated with basic string references to .txt files. Neither .activate() or regular select works. 

C:\noyb\projects\studd\lists\<VirtualEvent event x=0 y=0>.txt Sort
File not found: C:\noyb\projects\studd\lists\<VirtualEvent event x=0 y=0>.txt
Error opening file: [Errno 22] Invalid argument: 'C:\\noyb\\projects\\studd\\lists\\<VirtualEvent event x=0 y=0>.txt'

self.listbox = EditorListbox(self.bottom_frame, command=self.on_listbox_select) 

class EditorListbox(CTkListbox):
    def __init__(self, master, command=None, **kwargs)

        self.command = command
        
        self.bind("<<ListboxSelect>>", self.on_listbox_select)

    def unbind(self):
        self.unbind_all("<<ListboxSelect>>")

    def update_theme(self):
        self.configure(
            fg_color=listbox_fg_color, 
            highlight_color=listbox_select_color,  
            border_color=listbox_border_color, 
            hover_color=listbox_select_color,
            text_color = listbox_txt_color,
            scrollbar_button_color=scrollbar_color,
            scrollbar_button_hover_color=scrollbar_hover_color
        )

    def on_listbox_select(self, event):
        if self.command:
            self.command(event)

**Comment by infiniteTesch** [comment]
I made it work by using the .get() function instead of selection_option like so:
def on_listbox_select(self, selected_option): 

In this case i got VirtualEvent event x=0 y=0 as value for selected_option on click.

**Comment by Akascape** [comment]
@infiniteTesch `<<ListboxSelect>>` is only a trigger event which doesn't return/pass any value, you have to use `.get()` method in the function with this.
