### ISSUE TITLE
Support for exportselection=False/True

### ISSUE THREAD

**Issue by codedreamin** [Akascape/CTkListbox#5]
Hello,

Appreciate the work for this addition to customtkinter, I currently have a listbox inside of a tabview and when I tab back and forth it unhighlights the listbox selection.

Could exportselection be added as an option for CTkListbox?

**Comment by Akascape** [comment]
@codedreamin CTkListbox is a little different, it doesn't unhighlight the selections when other ctklistbox is focused, so there is no need of exportselection option. If you want to deselect something, use `.deselect()` method.

**Comment by codedreamin** [comment]
Thanks Akascape for the quick reply, it seems that it kept the selection highlighted after I added widgets to all three of my tabs. So although I'm not entirely sure why it was behaving that way. It is working now.
