### ISSUE TITLE
customtkinter light appearance mode makes the list items nearly invisible

### ISSUE THREAD

**Issue by Alex-Schaefer** [Akascape/CTkListbox#52]
Adding `customtkinter.set_appearance_mode("light")` to the provided example breaks the CTKListbox colors: Only the selected item and hovering items are visible. The other ones are barely visible.

In dark mode it works fine, but light mode is not usable:

![ctklistbox-light-broken](https://github.com/Akascape/CTkListbox/assets/81265029/8d49a465-ba91-4767-988e-eb2fef023302)

![ctklistbox-dark-works](https://github.com/Akascape/CTkListbox/assets/81265029/39cb532e-1917-40ef-bbd2-dd8cfe4be6df)

Setting a custom text_color tuple is a workaround, but in my opinion the default colors should work out of the box.

**Comment by Akascape** [comment]
@Alex-Schaefer  Fixed, update to new version.
