### ISSUE TITLE
List Scrollbar gets stuck when using .delete("all") to migrate from a bigger list to a small one, or am I doing something wrong?

### ISSUE THREAD

**Issue by tsouzadaSSA** [Akascape/CTkListbox#56]
The List scrollbar does not reset by itself when the list is deleted by using '.delete("all")'.
It is required to roll the scrollbar. Then, when a big list is loaded (ex.: 300 items), if it is rolled all the way down and reload a smaller list (delete all the items, then load smaller list), the scrollbar gets stuck.

**Comment by Akascape** [comment]
@tsouzadaSSA Fixed, update to new version.
