### ISSUE TITLE
cannot replace a line index

### ISSUE THREAD

**Issue by rottenCoprse** [Akascape/CTkListbox#59]
ten items in my listbox i want to replace index 5 listbox.delete(5) when i try insert(5,"frogs") it adds it to the end of the list? although it did delete index 5?

Its quite possible I'm doing something wrong? any help sure would be appreciated!

Thanks

**Comment by Akascape** [comment]
@rottenCoprse Update to latest version, I have fixed this by replacing pack with grid method.
