### ISSUE TITLE
Can curselection and activate methods be supported?

### ISSUE THREAD

**Issue by codedreamin** [Akascape/CTkListbox#6]
Are the base Tkinter Listbox methods curselection and activate, currently supported and if not could they be added? Thanks!

**Comment by Akascape** [comment]
@codedreamin can you explain what these options do?

**Comment by codedreamin** [comment]
@Akascape
yeah,

curselection()

Returns a tuple containing the line numbers of the selected element or elements, counting from 0. If nothing is selected, returns an empty tuple.

activate ( index )

Selects the line specifies by the given index.

The reason I ask is that I have a listbox of user created groups, I give them an option to give it an alias and when they do it deletes the old selection from the listbox and then re-adds it with the new alias.

When this happens the group witht he new alias name is no longer highlighted. I'm trying to figure out a solution for this. If there already exists a good solution to this issue that I don't know about I'd be happy to hear it.

Thanks!

**Comment by Akascape** [comment]
@codedreamin Ok thanks, I will try to add these options soon.

**Comment by Akascape** [comment]
@codedreamin Added curselection and activate methods. Please update (`pip install ctklistbox --upgrade`)

**Comment by codedreamin** [comment]
Great, thank you! Works great.
