### ISSUE TITLE
CTklistbox scrolling problem when creating more than one CTklistbox

### ISSUE THREAD

**Issue by DigitalCreationsLibrary** [Akascape/CTkListbox#8]
Hi,
First of all, thanks for the library, it saved the day (I needed CTklistboxes for my coding video, and you created one!).
I had this wired problem when I created two CTklistboxes, and when I inserted in both of them, only the last created one was scrolling properly. I tested with three CTklistboxes as well, and the same behavior happened: The two first two CTklistboxes where like fidgeted: the elements were added, but the scrollbar heigh wasn't adapting, so the scrolling became  impossible. 

To make the scrolling work properly, I had to comment out the definition of the **bind** method from your source code. And the scrolling worked for both CTklistboxes. I don't why it worked after commenting out the binding, and I don't know if there is something wrong with my code, but here is the code that generated the issue:

```
import customtkinter as ct
from customtkinter import *
from  CTkListbox import *

ct.set_appearance_mode("dark")
ct.set_default_color_theme("blue")

main_window=CTk()
main_window.geometry("600x400+250+200")
main_window.title("YouTube Videos Titles And Description")

firstList = CTkListbox(main_window,)
firstList.grid(row=0,column=0,padx=25,)


secondList = CTkListbox(main_window)
secondList.grid(row=0,column=1,padx=25,)


myIDs=range(20)


def getMyList():
    for id in myIDs:       
        firstList.insert("END",str(id)+" - list 1")
        secondList.insert("END",str(id)+" - list 2")
        secondList.update_idletasks()

getButton = CTkButton(main_window,text="Get The Titles & The Descriptions",
                      command=getMyList)
getButton.grid(row=1,column=1,padx=5,pady=10, sticky=E,)

main_window.mainloop()
```

Thanks again for the library, and for your time.

**Comment by Akascape** [comment]
@DigitalCreationsLibrary Fixed, update to the latest version. 

>I needed CTklistboxes for my coding video, and you created one!

Send me the link when you finished your video 😄

**Comment by DigitalCreationsLibrary** [comment]
> @DigitalCreationsLibrary Fixed, update to the latest version.
> 
> > I needed CTklistboxes for my coding video, and you created one!
> 
> Send me the link when you finished your video 😄

Thanks, it worked ! 🙂
