### ISSUE TITLE
listvariable error

### ISSUE THREAD

**Issue by notabxcksy** [Akascape/CTkListbox#9]
There is no listrvariable in CTkListbox, when will you add this feature?

**Comment by Akascape** [comment]
@notabxcksy Tell me what this option does, I will add it.

**Comment by notabxcksy** [comment]
@Akascape i dont know, i got chatgpt code and wanna recreate it with ctk and that not working, i can give u code if u wanna

**Comment by Akascape** [comment]
@notabxcksy Listvariable parameter added, update to the latest version `pip install ctklistbox --upgrade` and try.

**Comment by notabxcksy** [comment]
thank you very match
